# Generated by Django 2.1.15 on 2021-01-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingrediens',
            new_name='ingredients',
        ),
    ]
